service: ocr-backend

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-2
  stage: prod
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    S3_BUCKET: ${self:service}-${self:provider.stage}-temp
  timeout: 30
  memorySize: 1024
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: 
            - "arn:aws:logs:*:*:*"
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource: 
            - "arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*"

functions:
  api:
    handler: main.handler
    events:
      - http:
          path: /api/{proxy+}
          method: any
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
              - X-Amz-Date
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
            maxAge: 86400

resources:
  Resources:
    TempBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ['*']
              AllowedMethods: [GET, PUT]
              AllowedOrigins: ['*']
              MaxAge: 3000
        LifecycleConfiguration:
          Rules:
            - Id: DeleteOldFiles
              Status: Enabled
              ExpirationInDays: 1

package:
  patterns:
    - '!venv/**'
    - '!__pycache__/**'
    - '!*.pyc'
    - '!.git/**'
    - '!.gitignore'
    - '!.env'
    - '!.vscode/**'
    - '!.pytest_cache/**'
    - '!*.md'
    - '!requirements.txt'
    - '!serverless.yml'
    - 'fonts/NanumGothic.ttf'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    useDownloadCache: true
    useStaticCache: true 