service: ocr-backend

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-2
  stage: prod
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    S3_BUCKET: "ocr-temp-storage"
  timeout: 60
  memorySize: 3008
  vpc:
    securityGroupIds:
      - ${env:VPC_SECURITY_GROUP}
    subnetIds:
      - ${env:VPC_SUBNET_1}
      - ${env:VPC_SUBNET_2}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: 
            - "arn:aws:logs:*:*:*"
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
            - s3:ListBucket
          Resource: 
            - "arn:aws:s3:::${self:provider.environment.S3_BUCKET}"
            - "arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*"
        - Effect: Allow
          Action:
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DeleteNetworkInterface
          Resource: "*"

functions:
  api:
    handler: main.handler
    layers:
      - ${self:custom.tesseractLayer}
    events:
      - http:
          path: /api/{proxy+}
          method: any
          cors: true
    alarms:
      - name: highErrorRate
        description: 'High error rate'
        namespace: 'AWS/Lambda'
        metric: Errors
        threshold: 1
        period: 300
        evaluationPeriods: 1
        comparisonOperator: GreaterThanThreshold
        statistic: Sum
      - name: highDuration
        description: 'High duration'
        namespace: 'AWS/Lambda'
        metric: Duration
        threshold: 50000
        period: 300
        evaluationPeriods: 1
        comparisonOperator: GreaterThanThreshold
        statistic: Average

resources:
  Resources:
    ServerlessDeploymentBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ocr-backend-deployment
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        VersioningConfiguration:
          Status: Suspended
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256

    OcrStorageBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ['*']
              AllowedMethods: [GET, PUT, POST, DELETE, HEAD]
              AllowedOrigins: ['*']
              MaxAge: 3000
        LifecycleConfiguration:
          Rules:
            - Id: DeleteOldFiles
              Status: Enabled
              ExpirationInDays: 1

    OcrStorageBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref OcrStorageBucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: AllowLambdaAccess
              Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
                - s3:ListBucket
              Resource:
                - !Sub ${OcrStorageBucket.Arn}/*
                - !Sub ${OcrStorageBucket.Arn}

package:
  patterns:
    - '!venv/**'
    - '!__pycache__/**'
    - '!*.pyc'
    - '!.git/**'
    - '!.gitignore'
    - '!.env'
    - '!.vscode/**'
    - '!.pytest_cache/**'
    - '!*.md'
    - '!requirements.txt'
    - '!serverless.yml'
    - 'fonts/NanumGothic.ttf'

plugins:
  - serverless-python-requirements
  - serverless-plugin-lambda-layers

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    useDownloadCache: true
    useStaticCache: true
  tesseractLayer:
    name: tesseract-ocr
    description: Tesseract OCR layer
    compatibleRuntimes:
      - python3.9
    package:
      - tesseract
      - tesseract-langpack-kor 